[package]
name = "sudoku_solver_core"
version = "0.1.0"
authors = ["Toshiki <toshiki.dev@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
